services:
  db:
    image: postgres:16-alpine
    container_name: final_db_container
    environment:
      POSTGRES_DB: final_new_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d finalnew_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: final_app_container
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/final_new_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "1234"
      SPRING_FLYWAY_ENABLED: "true"

volumes:
  postgres_data: