CREATE TABLE t_category (
                            id BIGSERIAL PRIMARY KEY,
                            name VARCHAR(255)
);

CREATE TABLE t_country (
                           id BIGSERIAL PRIMARY KEY,
                           code VARCHAR(10) NOT NULL,
                           name VARCHAR(255) NOT NULL
);

CREATE TABLE t_item (
                        id BIGSERIAL primary key,
                        name VARCHAR(255) NOT NULL,
                        price int,
                        description VARCHAR(255) NOT NULL,
                        category_id BIGINT,
                        FOREIGN KEY (category_id) REFERENCES t_category(id)
);

CREATE TABLE t_item_countries (
                                  item_id BIGINT NOT NULL,
                                  countries_id BIGINT NOT NULL,
                                  PRIMARY KEY (item_id, countries_id),
                                  FOREIGN KEY (item_id) REFERENCES t_item(id),
                                  FOREIGN KEY (countries_id) REFERENCES t_country(id)
);
CREATE TABLE t_permissions (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               name VARCHAR(255) NOT NULL UNIQUE
);
INSERT INTO t_permissions (name) VALUES ('ROLE_USER');
INSERT INTO t_permissions (name) VALUES ('ROLE_ADMIN');
CREATE TABLE t_users (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         email VARCHAR(255) NOT NULL UNIQUE,
                         password VARCHAR(255) NOT NULL
);
CREATE TABLE t_users_permissions (
                                     user_id BIGINT NOT NULL REFERENCES t_users (id),
                                     permissions_id BIGINT NOT NULL REFERENCES t_permissions (id),
                                     PRIMARY KEY (user_id, permissions_id)
);